### ISSUE TITLE
Day 2.1

### ISSUE THREAD

**Issue by csherwood-usgs** [dbuscombe-usgs/cdi_dl_workshop#2] opened 2018-07-08 18:18 UTC
The other models don't run. (e.g., starting at Cell 33). They produce:

```
An exception has occurred, use %tb to see the full traceback.

SystemExit: 2
```
A full traceback produces:
```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
/opt/conda/lib/python3.6/argparse.py in _get_value(self, action, arg_string)
   2289         try:
-> 2290             result = type_func(arg_string)
   2291 

ValueError: invalid literal for int() with base 10: '$num_steps'

During handling of the above exception, another exception occurred:

ArgumentError                             Traceback (most recent call last)
/opt/conda/lib/python3.6/argparse.py in parse_known_args(self, args, namespace)
   1761         try:
-> 1762             namespace, args = self._parse_known_args(args, namespace)
   1763             if hasattr(namespace, _UNRECOGNIZED_ARGS_ATTR):

/opt/conda/lib/python3.6/argparse.py in _parse_known_args(self, arg_strings, namespace)
   1967             # consume the next optional and any arguments for it
-> 1968             start_index = consume_optional(start_index)
   1969 

/opt/conda/lib/python3.6/argparse.py in consume_optional(start_index)
   1907             for action, args, option_string in action_tuples:
-> 1908                 take_action(action, args, option_string)
   1909             return stop

/opt/conda/lib/python3.6/argparse.py in take_action(action, argument_strings, option_string)
   1819             seen_actions.add(action)
-> 1820             argument_values = self._get_values(action, argument_strings)
   1821 

/opt/conda/lib/python3.6/argparse.py in _get_values(self, action, arg_strings)
   2260             arg_string, = arg_strings
-> 2261             value = self._get_value(action, arg_string)
   2262             self._check_value(action, value)

/opt/conda/lib/python3.6/argparse.py in _get_value(self, action, arg_string)
   2302             msg = _('invalid %(type)s value: %(value)r')
-> 2303             raise ArgumentError(action, msg % args)
   2304 

ArgumentError: argument --how_many_training_steps: invalid int value: '$num_steps'

During handling of the above exception, another exception occurred:

SystemExit                                Traceback (most recent call last)
/opt/conda/lib/python3.6/site-packages/IPython/utils/py3compat.py in execfile(fname, glob, loc, compiler)
    186     with open(fname, 'rb') as f:
    187         compiler = compiler or compile
--> 188         exec(compiler(f.read(), fname, 'exec'), glob, loc)
    189 
    190 # Refactor print statements in doctests.

~/cdi_dl_workshop/Day2/retrain.py in <module>()
   1330       default='',
   1331       help='Where to save the exported graph.')
-> 1332   FLAGS, unparsed = parser.parse_known_args()
   1333   tf.app.run(main=main, argv=[sys.argv[0]] + unparsed)

/opt/conda/lib/python3.6/argparse.py in parse_known_args(self, args, namespace)
   1767         except ArgumentError:
   1768             err = _sys.exc_info()[1]
-> 1769             self.error(str(err))
   1770 
   1771     def _parse_known_args(self, arg_strings, namespace):

/opt/conda/lib/python3.6/argparse.py in error(self, message)
   2387         self.print_usage(_sys.stderr)
   2388         args = {'prog': self.prog, 'message': message}
-> 2389         self.exit(2, _('%(prog)s: error: %(message)s\n') % args)

/opt/conda/lib/python3.6/argparse.py in exit(self, status, message)
   2374         if message:
   2375             self._print_message(message, _sys.stderr)
-> 2376         _sys.exit(status)
   2377 
   2378     def error(self, message):

SystemExit: 2

```

**Comment by ddbuscombe** [comment] 2018-07-08 18:30
I can't reproduce the error (which is that ```num_steps``` is not defined). Did you run the cell that sets this and the learning rate parameter?

**Comment by ddbuscombe** [comment] 2018-07-08 18:55
Oh, I see where you are. Fixing now ... and closing

**Closed as completed by ddbuscombe** 2018-07-08 18:55 UTC
